/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LogInDialog.java
 *
 * Created on Nov 15, 2011, 5:09:29 PM
 */
package yoreportero.frameset;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.SQLException;
import yoreportero.database.YoReporteroConnection;

/**
 *
 * @author alonso
 */
public class dialogLogin extends javax.swing.JDialog {

    YoReporteroConnection connection;
    private boolean correct = false;
    private String username;

    /** Creates new form LogInDialog */
    public dialogLogin(java.awt.Frame parent, boolean modal, YoReporteroConnection connection) {
        super(parent, modal);
        this.connection = connection;
        initComponents();
        this.HideError();
        try {
            java.io.File userfile = new File("user");
            if (userfile.exists()) {
                checkRememberUsername.setSelected(true);
                UsernameText.setText(readFileAsString("user"));
                java.io.File passfile = new File("pass");
                if (passfile.exists()) {
                    checkRememberPassword.setSelected(true);
                    PasswordText.setText(readFileAsString("pass"));
                }
            }
        } catch (Exception ex) {
        }
    }
    
        /** @param filePath the name of the file to open. Not sure if it can accept URLs or just filenames. Path handling could be better, and buffer sizes are hardcoded
    */ 
    private String readFileAsString(String filePath)
    throws java.io.IOException{
        StringBuilder fileData = new StringBuilder(1000);
        BufferedReader reader = new BufferedReader(
                new FileReader(filePath));
        char[] buf = new char[1024];
        int numRead=0;
        while((numRead=reader.read(buf)) != -1){
            String readData = String.valueOf(buf, 0, numRead);
            fileData.append(readData);
            buf = new char[1024];
        }
        reader.close();
        return fileData.toString();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UsernameText = new javax.swing.JTextField();
        CancelButton = new javax.swing.JButton();
        OkButton = new javax.swing.JButton();
        PasswordText = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        labelError = new javax.swing.JLabel();
        checkRememberUsername = new javax.swing.JCheckBox();
        checkRememberPassword = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Login");
        setResizable(false);

        CancelButton.setText("Cancel");
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });

        OkButton.setText("Ok");
        OkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OkButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 14));
        jLabel1.setText("Nombre de usuario");

        jLabel2.setFont(new java.awt.Font("Ubuntu", 0, 14));
        jLabel2.setText("Contraseña");

        labelError.setForeground(new java.awt.Color(255, 0, 0));
        labelError.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelError.setText("Errores");

        checkRememberUsername.setText("Recordar Nombre de usuario");
        checkRememberUsername.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                checkRememberUsernameStateChanged(evt);
            }
        });

        checkRememberPassword.setText("Recordar Contraseña");
        checkRememberPassword.setEnabled(false);

        jLabel3.setForeground(java.awt.Color.blue);
        jLabel3.setText("¿Olvidó su contraseña?");
        jLabel3.setToolTipText("Función no disponible.");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.setFocusCycleRoot(true);

        jLabel4.setForeground(java.awt.Color.blue);
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Registrarse");
        jLabel4.setToolTipText("");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.setFocusCycleRoot(true);
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(UsernameText, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(PasswordText, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
                    .addComponent(labelError, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(OkButton, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CancelButton, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE))
                    .addComponent(checkRememberUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
                    .addComponent(checkRememberPassword, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UsernameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PasswordText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkRememberUsername)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkRememberPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(labelError)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OkButton)
                    .addComponent(CancelButton))
                .addContainerGap())
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-386)/2, (screenSize.height-280)/2, 386, 280);
    }// </editor-fold>//GEN-END:initComponents

    private void ShowError(String text) {
        labelError.setText(text);
    }

    private void HideError() {
        labelError.setText("");
    }

    private void OkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OkButtonActionPerformed
        String user = UsernameText.getText();
        String pass = new String(PasswordText.getPassword());
        if (!user.equals("") && !pass.equals("")) {
            String q = "select contrasenna from usuario where nombre_usuario = '" + user + "';";
            try {
                ResultSet ejecutarConsulta = connection.ejecutarConsulta(q);
                if (ejecutarConsulta.next()) {
                    if (ejecutarConsulta.getString(1).equals(pass)) {
                        this.correct = true;
                        this.username = user;
                        java.io.File userfile = new File("user");
                        if (checkRememberUsername.isSelected()) {
                            java.io.FileWriter fw = new FileWriter(userfile);
                            fw.write(user);
                            fw.close();
                            java.io.File passfile = new File("pass");
                            if (checkRememberPassword.isEnabled()) {
                                fw = new FileWriter(passfile);
                                fw.write(pass);
                                fw.close();
                            } else {
                                passfile.delete();
                            }
                        } else {
                            userfile.delete();
                        }
                        this.setVisible(false);
                        this.dispose();
                    } else {
                        ShowError("Contraseña incorrecta");
                    }
                } else {
                    ShowError("El usuario no existe");
                }
            } catch (SQLException sqlEX) {
                ShowError("Imposible establecer la conexión con la base de datos");
                System.out.println(q);
            } catch (IOException ioex) {
            }
        } else {
            ShowError("El nombre de usuario o contraseña está vacío");
        }
    }//GEN-LAST:event_OkButtonActionPerformed

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_CancelButtonActionPerformed

    private void checkRememberUsernameStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_checkRememberUsernameStateChanged
        checkRememberPassword.setEnabled(checkRememberUsername.isSelected());
        if (!checkRememberUsername.isSelected())
            checkRememberPassword.setSelected(false);
    }//GEN-LAST:event_checkRememberUsernameStateChanged

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        dialogNewUser dnu = new dialogNewUser(null, true, connection);
        dnu.setVisible(true);
    }//GEN-LAST:event_jLabel4MouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelButton;
    private javax.swing.JButton OkButton;
    private javax.swing.JPasswordField PasswordText;
    private javax.swing.JTextField UsernameText;
    private javax.swing.JCheckBox checkRememberPassword;
    private javax.swing.JCheckBox checkRememberUsername;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel labelError;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the correct
     */
    public boolean isCorrect() {
        return correct;
    }

    /**
     * @return the usuario
     */
    public String getUsuario() {
        return username;
    }
}
