/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * dialogProfile.java
 *
 * Created on Nov 25, 2011, 8:13:09 AM
 */
package yoreportero.frameset;

import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.DefaultListModel;

/**
 *
 * @author alonso
 */
public final class dialogProfile extends javax.swing.JDialog {

    yoreportero.database.YoReporteroConnection conn;
    String seguidor;
    String seguido;

    /** Creates new form dialogProfile */
    public dialogProfile(java.awt.Frame parent, boolean modal, yoreportero.database.YoReporteroConnection connection,
            String follower, String followed) {
        super(parent, modal);
        initComponents();
        conn = connection;
        seguidor = follower;
        seguido = followed;
        Actualizar();
        ComprobarSigue();
    }

    // Actualiza los posts del usuario visto
    public void Actualizar() {
        try {
            ResultSet rs = conn.ejecutarConsulta("select contenido from post where nombre_usuario = '" + seguido + "';");
            DefaultListModel dlm = new DefaultListModel();
            while (rs.next()) {
                dlm.addElement(rs.getString("contenido"));
            }
            listPost.setModel(dlm);
            jLabel1.setText(seguido);
        } catch (Exception e) {
        }
    }

    // Comprueba si el usuario que inicia sesión sigue al que se ve actualmente
    public void ComprobarSigue() {
        try {
            ResultSet rs = conn.ejecutarConsulta("select seguidor from sigue where seguidor = '"
                    + seguidor + "' and seguido = '" + seguido + "';");
            if (rs.next()) {
                jToggleButton1.setText("Dejar de seguir");
                jToggleButton1.setSelected(true);
            } else {
                jToggleButton1.setText("Seguir");
                jToggleButton1.setSelected(true);
            }
        } catch (Exception e) {
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listPost = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jToggleButton1.setText("Seguir");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jLabel1.setText("jLabel1");

        listPost.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listPost);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 568, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jToggleButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        try {
            ResultSet rs = conn.ejecutarConsulta("select seguidor from sigue where seguidor = '"
                    + seguidor + "' and seguido = '" + seguido + "';");
            if (rs.next()) {
                jToggleButton1.setText("Seguir");
                jToggleButton1.setSelected(false);
                conn.ejecutarConsulta("delete from sigue where "
                        + "seguidor = '" + seguidor + "' and seguido = '" + seguido + "';");
            } else {
                jToggleButton1.setText("Dejar de seguir");
                jToggleButton1.setSelected(true);
                conn.ejecutarConsulta("insert into sigue(seguidor, seguido) values "
                        + "('" + seguidor + "', '" + seguido + "');");
            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JList listPost;
    // End of variables declaration//GEN-END:variables
}
